#!/usr/bin/perl
use 5.014;
use warnings;

my @test = (1..105);

foreach( @test ) {
    print "\nProcessing $_ ";
    when ( $_ % 3 == 0 ) { print "Fizz"; continue }
    when ( $_ % 5 == 0 ) { print "Bin"; continue }
    when ( $_ % 7 == 0 ) { print "Sausage" }
    default {}
}