#!/usr/bin/perl
use 5.010;
use warnings;

my @fred = above_average(1..10);
print "\@fred is @fred\n";
print "(Should be 6 7 8 9 10)\n";
my @barney = above_average(100, 1..10);
print "\@barney is @barney\n";
print "(Should be just 100)\n";


sub average {
  $sum = 0;
  $count = 0;
  foreach (@_) {
    $sum = $sum + $_;
    $count += 1;
  }
  return $sum/$count;
}

sub above_average {
  @range = @_;
  $average = &average(@range);

  foreach $_ (@range) {
    if ($_ > $average) {
      print $_;
    }
  }
}
