#!/usr/bin/perl
use 5.010;
use warnings;
use DateTime;

print "Please enter any date (historical or future) in the form MMDDYYYY: \n";
chomp(my $dt = <STDIN>);

$dt->subtract datetime ($datetime)
$dt->delta days ($datetime)